# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "k8s-master"
  config.vm.network "private_network", ip: "192.168.56.225",
    auto_config: false

  config.vm.provider "hyperv" do |hv|
    hv.vmname = "k8s-master"
    hv.memory = 4096
    hv.cpus = 2
  end
  # config.vm.provision "shell", path: "scripts/k8s-master-install.sh"
end
