# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.hostname = "kubernetes-srv"
  config.vm.network :private_network, ip: "192.168.56.225"
  config.vm.provider "hyperv" do |hv|
    hv.vmname = "k8s-master"
    hv.memory = 4096
    hv.cpus = 2
  end
  config.vm.provision "shell", path: "k8s-master-install.sh"
end
